//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by guana.rc
//
#define IDS_ABOUTBOX                    1
#define IDOK2                           3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_GUANA_DIALOG                102
#define IDD_DLG_SEARCH_GUEST            103
#define IDD_TSPASHDLG_DIALOG            104
#define IDD_TDEPOSIT_DLG_DIALOG         105
#define IDD_DIALOG_TECH                 106
#define IDD_DIALOG_BILL                 107
#define IDD_DIALOG_TIME                 108
#define IDD_TGUESTADD_DIALOG            109
#define IDD_TBILLADD_DIALOG             110
#define IDR_MAINFRAME_I                 128
#define IDR_MAINFRAME                   128
#define IDR_ACCELERATOR1                129
#define IDD_DIALOG_CONNECT              133
#define IDB_BITMAP_ADD                  136
#define IDB_BITMAP_PRIV                 137
#define IDB_BITMAP_OK                   138
#define IDB_BITMAP_NEXT                 139
#define IDB_BITMAP_END                  140
#define IDB_BITMAP_EDIT                 141
#define IDB_BITMAP_DEL                  142
#define IDB_BITMAP_CANCEL               143
#define IDB_BITMAP_BEGIN                144
#define IDB_BITMAP_REFRESH              145
#define IDD_DIALOG_MANY_TO_MANY         146
#define IDD_DIALOG_LOOKUP               149
#define IDB_BITMAP_PRT                  150
#define ID_CMD_GUEST                    150
#define IDD_DIALOG_COMMENTS             151
#define ID_CMD_BILL                     151
#define IDD_BILLRPTSELECT               153
#define IDD_DIALOG_RECREATE             154
#define IDD_DIALOG_LOGIN                155
#define IDB_BITMAP_WIZ                  156
#define IDC_TAB1                        1000
#define IDC_EXIT                        1003
#define IDC_ROOM                        1006
#define IDC_DATAGRID_ROOM               1007
#define IDC_DATAGRID_BILLCAT            1008
#define IDC_DATAGRID_GUESTCAT           1009
#define IDC_DATAGRID_RECOMMBILLCAT      1010
#define IDC_DATAGRID_T2                 1010
#define IDC_DC_ROOM                     1011
#define IDC_DC_BILLCAT                  1012
#define IDC_DC_T2                       1012
#define IDC_DC_CATPAY                   1012
#define IDC_DC_GUESTCAT                 1013
#define IDC_DC_BILL                     1013
#define IDC_DC_RECOMMBILLCAT            1014
#define IDC_STATIC_ROOM                 1015
#define IDC_STATIC_ALLGCAT              1016
#define IDC_EDIT_SERVER                 1016
#define IDC_STATIC_LCAT                 1017
#define IDC_EDIT_US                     1017
#define IDC_RADIO_WINNT                 1018
#define IDC_RADIO3                      1019
#define IDC_EDIT_PWD                    1020
#define IDC_EDIT_DBNAME                 1021
#define IDC_STATIC_USER                 1022
#define IDC_STATIC_SELGCAT              1023
#define IDC_STATIC_PWD                  1023
#define IDC_BTN_EDITREC                 1025
#define IDC_BUTTON_REM                  1027
#define IDC_BUTTON_ADD                  1028
#define IDC_DATAGRID_T1                 1029
#define IDC_DC_T1                       1030
#define IDC_DATAGRID_GUEST              1033
#define IDC_DATAGRID_BILL               1034
#define IDC_DATAGRID_ADDCHARGES         1035
#define IDC_RADIO_NAM                   1037
#define IDC_RADIO_RATE                  1038
#define IDC_DATAGRID_PAYMENTS           1038
#define IDC_RADIO_FNAM                  1039
#define IDC_RADIO_CITY                  1040
#define IDC_RADIO_CAT                   1041
#define IDC_STATIC_GUEST                1042
#define IDC_RADIO_DEPOSIT               1043
#define IDC_DC_GUEST                    1044
#define IDC_STATIC_BILL                 1045
#define IDC_RADIO_DATE                  1046
#define IDC_RADIO_FOLIO                 1047
#define IDC_RADIO_NIGHTS                1048
#define IDC_RADIO_BALANCEDUE            1049
#define IDC_DATAGRID_ROOMSALLOC         1050
#define IDC_DC_ADDCHARGES               1051
#define IDC_DC_PAYMENTS                 1052
#define IDC_DC_ROOMSALLOC               1053
#define IDC_DC_CATEGORY_G               1054
#define IDC_MASKEDBOX_BILLNO            1055
#define IDC_DTPICKER_DATE               1056
#define IDC_MASKEDBOX_FOLIO             1057
#define IDC_BUTTON_PAYENROL             1059
#define IDC_MASKEDBOX_GI                1060
#define IDC_MASKEDBOX_DETAILS           1061
#define IDC_BUTTON_MONEYBACK            1062
#define IDC_MASKEDBOX_TOTALADD          1063
#define IDC_MASKEDBOX_PAYMENTS          1064
#define IDC_MASKEDBOX_TOTALROOMS        1065
#define IDC_MASKEDBOX_SUBTOTAL          1066
#define IDC_MASKEDBOX_TAXANDSERV        1067
#define IDC_MASKEDBOX_TOTAL             1068
#define IDC_MASKEDBOX_DEPOSIT           1069
#define IDC_BUTTON_SEARCH               1070
#define IDC_MASKEDBOX_BALANCEDUE        1071
#define IDC_BUTTON_COMMENT              1072
#define IDC_LIST                        1073
#define IDC_EDIT_FOLIO                  1074
#define IDC_EDIT_BILLNO                 1075
#define IDC_EDIT_GI                     1077
#define IDC_EDIT_DETAILS                1078
#define IDC_EDIT_TOTALADD               1079
#define IDC_EDIT_PAYMENTS               1080
#define IDC_EDIT_TAXANDSERV             1081
#define IDC_EDIT_TOTAL                  1082
#define IDC_EDIT_DEPOSIT                1083
#define IDC_EDIT_BALANCEDUE             1084
#define IDC_EDIT_TOTALROOMS             1085
#define IDC_EDIT_SUBTOTAL               1086
#define IDC_PICK_DATE                   1089
#define IDC_BUTTON_PRT                  1090
#define IDC_BUTTON_WIZ                  1090
#define IDC_EDIT_TXT                    1091
#define IDC_BUTTON_PRT2                 1091
#define IDC_DC_GB                       1092
#define IDC_DATAGRID_GB                 1093
#define IDC_RADIO_ALL                   1095
#define IDC_RADIO_SEL                   1096
#define IDC_DATETIMEPICKER1             1097
#define IDC_DATETIMEPICKER2             1098
#define IDC_DATETIMEPICKER_DATETO       1099
#define IDC_BUTTON_REPORT               1100
#define IDC_STATIC_GB                   1101
#define IDC_BUTTON_REFILL               1102
#define IDC_DATALIST_CAT                1103
#define IDC_STATIC_FRAME                1104
#define IDC_RADIO_ORDINAL               1105
#define IDC_RADIO_PRETTY                1106
#define IDC_BTN_RECREATE                1108
#define IDC_EDIT_PATH                   1109
#define IDC_EDIT_DSIZE                  1110
#define IDC_EDIT_LSIZE                  1111
#define IDC_EDIT_PASSW                  1112
#define IDC_BUTTON_JUMP                 1113
#define IDC_EDIT_FNAME                  1114
#define IDC_EDIT_LNAME                  1115
#define IDC_STATIC_M1                   1115
#define IDC_STATIC_P1                   1116
#define IDC_STATIC_EQ1                  1117
#define IDC_STATIC_P2                   1118
#define IDC_STATIC_EQ2                  1119
#define IDC_BUTTON_REMOVE               1120
#define IDC_PROGRESS1                   1121
#define IDC_STATIC_TTL                  1122
#define IDC_EDIT_DEPOS                  1123
#define IDC_BUTTON_SUB                  1124
#define IDC_STATIC_1                    1125
#define IDC_STATIC_2                    1126
#define IDC_STATIC_3                    1127
#define IDC_STATIC_4                    1128
#define IDC_STATIC_5                    1129
#define IDC_STATIC_6                    1130
#define IDC_STATIC_7                    1131
#define IDC_STATIC_9                    1132
#define IDC_STATIC_20                   1133
#define IDC_STATIC_21                   1134
#define IDC_STATIC_22                   1135
#define IDC_STATIC_23                   1136
#define IDC_STATIC_24                   1137
#define IDC_DATACOMBO_CAT               1138
#define IDC_EDIT_ADDRESS                1142
#define IDC_EDIT_CITY                   1143
#define IDC_EDIT_POST                   1144
#define IDC_COMBO_STATE                 1145
#define IDC_EDIT_COMMENTS               1146
#define IDC_DATACOMBO_ROOM              1152
#define IDC_EDIT_NOOFGUESTS             1153
#define IDC_SPIN1                       1154
#define IDC_DATETIMEPICKER_DATE         1155
#define IDC_DATETIMEPICKER_DATEFROM     1156
#define ID_CANCEL                       32771
#define ID_OK                           32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1157
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
