#if !defined(AFX_PICTURE10_H__65EF0671_DD00_11D2_AD81_00504E02C39D__INCLUDED_)
#define AFX_PICTURE10_H__65EF0671_DD00_11D2_AD81_00504E02C39D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPicture10 wrapper class

class CPicture10 : public COleDispatchDriver
{
public:
	CPicture10() {}		// Calls COleDispatchDriver default constructor
	CPicture10(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPicture10(const CPicture10& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetHandle();
	long GetHPal();
	void SetHPal(long);
	short GetType();
	long GetWidth();
	long GetHeight();

// Operations
public:
	// method 'Render' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PICTURE10_H__65EF0671_DD00_11D2_AD81_00504E02C39D__INCLUDED_)
